### ISSUE TITLE
qb-target not working

### ISSUE THREAD

**Issue by frigg007** [trclassic92/tr-lumberjack#3]
Hello, I am unable to get qb-target to work with the peds. I do not have any errors in the f8 menu and not sure what is going on or if I need to add the models into qb-target themselves

**Comment by trclassic92** [comment]
> Hello, I am unable to get qb-target to work with the peds. I do not have any errors in the f8 menu and not sure what is going on or if I need to add the models into qb-target themselves

This issue could be caused by a few things..

 the first one could be if your target is out of date.  (if so then I would suggest that you update to the lastest one or at least convert the current one that you are using to the newer verison of qb-target. 

The second issue could be caused by if you are enabling it to be a job and your ped doesnt have the job to interact with the peds. Because then it becomes a job requirement to interact with the props / peds

also.. within most of the scripts I make / design qb-target with always have a export built into the script and by that I mean you will not have to do anything other then plug and play and change a few config options to your liking.

As far as the target it seems to be working fine on the lastest qb-target
